
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pro
 */
public class DataEntryForm extends java.awt.Frame {

    /**
     * Creates new form DataEntryForm
     */
    public DataEntryForm() {
        initComponents();
        setSize(400,400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        textField2 = new java.awt.TextField();
        label3 = new java.awt.Label();
        textField3 = new java.awt.TextField();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("EmpNo");
        add(label1);
        label1.setBounds(120, 70, 50, 20);
        add(textField1);
        textField1.setBounds(220, 70, 90, 20);

        label2.setText("EName");
        add(label2);
        label2.setBounds(120, 110, 46, 20);
        add(textField2);
        textField2.setBounds(220, 110, 90, 20);

        label3.setText("Salary");
        add(label3);
        label3.setBounds(120, 150, 38, 20);
        add(textField3);
        textField3.setBounds(220, 150, 90, 20);

        button1.setLabel("Save");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(190, 220, 57, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        try{
            String s1=textField1.getText();
            String s2=textField2.getText();
            String s3=textField3.getText();
            String sql="insert into emp values(?,?,?)";
            Connection con=DataUtility.connect();
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(s1));
            ps.setString(2, s2);
            ps.setInt(3, Integer.parseInt(s3));
            ps.executeUpdate();
            con.close();
            textField1.setText("");
            textField2.setText("");
            textField3.setText("");
            textField1.requestFocus();
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}

